
amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AKIAWPZFLV6DVIVPHYVI
  secretKey: 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
  bucketName: rovo.bucket
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB