
amazonProperties:
  endpointUrl: https://s3.ap-south-1.amazonaws.com
  accessKey: AXXXXXXXXXXXXXXXXXXXXI
  secretKey: jXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXF
  bucketName: roXX.XXXX
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
